# Generated by Django 3.1.5 on 2021-02-07 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terminal_1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useruserfollow',
            name='userid_followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useruserfollow',
            name='userid_follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercommentlike',
            name='commentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.comment'),
        ),
        migrations.AddField(
            model_name='usercommentlike',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercharartlike',
            name='character_artid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.characterart'),
        ),
        migrations.AddField(
            model_name='usercharartlike',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercharartbookmark',
            name='character_artid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.characterart'),
        ),
        migrations.AddField(
            model_name='usercharartbookmark',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercharacterlike',
            name='characterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.character'),
        ),
        migrations.AddField(
            model_name='usercharacterlike',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercharacterfollow',
            name='characterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.character'),
        ),
        migrations.AddField(
            model_name='usercharacterfollow',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_sectionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_comment_section', to='terminal_1.commentsection'),
        ),
        migrations.AddField(
            model_name='chararttag',
            name='character_artid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.characterart'),
        ),
        migrations.AddField(
            model_name='charartcharartrelationship',
            name='character_artid_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char_art_child', to='terminal_1.characterart'),
        ),
        migrations.AddField(
            model_name='charartcharartrelationship',
            name='character_artid_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char_art_parent', to='terminal_1.characterart'),
        ),
        migrations.AddField(
            model_name='characterlikes',
            name='characterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.character'),
        ),
        migrations.AddField(
            model_name='characterhates',
            name='characterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.character'),
        ),
        migrations.AddField(
            model_name='characterart',
            name='characterid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char_art_char', to='terminal_1.character'),
        ),
        migrations.AddField(
            model_name='characterart',
            name='comment_sectionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_art_comment_section', to='terminal_1.commentsection', unique=True),
        ),
        migrations.AddField(
            model_name='characterart',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_art_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='genderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.gender'),
        ),
        migrations.AddField(
            model_name='character',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
