# Generated by Django 3.1.5 on 2021-02-15 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_1', '0002_auto_20210215_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='charartcharartrelationship',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charartcharartrelationship',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
