# Generated by Django 3.1.5 on 2021-02-04 08:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_1', '0002_auto_20210204_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('genderid', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('characterid', models.AutoField(primary_key=True, serialize=False)),
                ('character_name', models.CharField(blank=True, max_length=50)),
                ('character_age', models.CharField(blank=True, max_length=25)),
                ('character_species', models.CharField(blank=True, max_length=25)),
                ('character_background', models.TextField(blank=True)),
                ('character_birthday', models.DateField(blank=True, null=True)),
                ('character_height', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('character_dialogue', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('genderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.gender')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
