# Generated by Django 3.1.5 on 2021-02-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_1', '0003_auto_20210215_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactertag',
            name='tag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chararttag',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
