# Generated by Django 3.1.5 on 2021-02-04 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_1', '0003_auto_20210204_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSection',
            fields=[
                ('comment_sectionid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterArt',
            fields=[
                ('character_artid', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('characterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_art_char', to='terminal_1.character')),
                ('comment_sectionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_art_comment_section', to='terminal_1.commentsection')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_art_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
