# Generated by Django 3.1.5 on 2021-02-15 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terminal_1', '0004_auto_20210215_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_tag',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='characterart',
            name='character_art_tag',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charactertag',
            name='userid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chararttag',
            name='userid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
            preserve_default=False,
        ),
    ]
