# Generated by Django 3.1.5 on 2021-02-04 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_1', '0005_charartcharartrelationship_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_height',
            field=models.BigIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
