# Generated by Django 3.1.5 on 2021-02-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_1', '0005_auto_20210215_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterart',
            name='character_hates',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='characterart',
            name='character_likes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
