# Generated by Django 3.1.5 on 2021-02-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_1', '0009_auto_20210204_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charartcharartrelationship',
            name='character_artid',
        ),
        migrations.AddField(
            model_name='charartcharartrelationship',
            name='character_artid_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char_art_child', to='terminal_1.characterart'),
        ),
        migrations.AddField(
            model_name='charartcharartrelationship',
            name='character_artid_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char_art_parent', to='terminal_1.characterart'),
        ),
    ]
