# Generated by Django 3.1.5 on 2021-02-04 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_1', '0010_auto_20210204_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid_followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_followed', to=settings.AUTH_USER_MODEL)),
                ('userid_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCharacterLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.character')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCharacterFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.character')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharArtTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('character_artid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.characterart')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.CharField(max_length=100)),
                ('characterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterHates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hates', models.CharField(max_length=100)),
                ('characterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.character')),
            ],
        ),
    ]
