# Generated by Django 3.1.5 on 2021-02-04 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_1', '0011_characterhates_characterlikes_chararttag_usercharacterfollow_usercharacterlike_useruserfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.comment')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCharArtLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_artid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.characterart')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCharArtBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_artid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_1.characterart')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
