# Generated by Django 3.1.5 on 2021-02-04 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_1', '0012_usercharartbookmark_usercharartlike_usercommentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterart',
            name='comment_sectionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_art_comment_section', to='terminal_1.commentsection', unique=True),
        ),
    ]
