# Generated by Django 3.1.5 on 2021-02-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='admin', max_length=15, verbose_name='user name'),
            preserve_default=False,
        ),
    ]
