from django.urls import path
from . import views

urlpatterns = [
    path('createchar/', views.UserCreateCharacterView.as_view()),
    path('char/changedetails/', views.UserCreatedCharacterDetailsView.as_view()),
    path('creategender/', views.AdminCreateGenderView.as_view()),
    path('createcharart/', views.UserCreateCharacterArtView.as_view()),
    path('charart/changedetails/', views.UserCreatedCharacterArtDetailsView.as_view()),
    path('createcomment/', views.UserCreateCommentView.as_view()),
    path('comment/changedetails/', views.UserCreatedCommentDetailsView.as_view()),
    path('createcommentlike/', views.UserLikeCommentView.as_view()),
    path('followcharacter/', views.UserFollowCharacterView.as_view()),
    path('likecharart/', views.UserLikeCharacterArtView.as_view()),
    path('followuser/', views.UserUserFollowView.as_view()),
    path('bookmarkcharart/', views.UserCharArtBookmarkView.as_view()),
    path('userdetails/', views.UserGetUserView.as_view()),
    path('charart/', views.UserGetCharacterArtView.as_view()),
    path('char/', views.UserGetCharacterView.as_view()),
    path('charart/comments/', views.UserGetCommentView.as_view()),
    path('charart/comments/responses/', views.UserGetCommentResponseView.as_view()),
    path('createcommentresponse/', views.UserCreateCommentResponseView.as_view()),
    path('commentresponse/changedetails/', views.UserCreatedCommentResponseDetailsView.as_view()),
    path('createcharartchild/', views.UserCreateCharArtCharArtRelationshipView.as_view()),
    path('childcharart/', views.UserGetChildCharArtView.as_view()),
    path('createchartags/', views.UserCreateCharTagsView.as_view()),
    path('createchararttags/', views.UserCreateCharArtTagsView.as_view()),
    path('usercharartbookmarks/', views.UserGetBookmarksOfUsersView.as_view()),
    path('userfollowing/', views.UserGetUserFollowingView.as_view()),
    path('userfollowingchar/', views.UserGetUserFollowingCharView.as_view()),
    path('charcount/', views.UserGetCharCountView.as_view()),
    path('charartcount/', views.UserGetCharArtCountView.as_view()),
    path('commentcount/', views.UserGetCommentCountView.as_view()),
    path('usercount/', views.UserGetUserCountView.as_view()),
    path('checkchararturl/', views.UserGetCharArtUrlView.as_view()),
    path('addCharartPageViews/', views.UserViewCharartView.as_view()),
    path('addCharPageViews/', views.UserViewCharView.as_view()),
]